# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0005_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='depth',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='family',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='order_in_parent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='weblog.Category'),
        ),
    ]
